title: Eric Wang
description: a curious mood
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github_url: https://www.github.com/ericewang/
linkedin_url: https://www.linkedin.com/in/ericewang/
resume_path: /assets/ericwang-resume.pdf
personal_email: eric.ej.wang@gmail.com
paginate: 5